import type { UserRole } from "@prisma/client";

import {
  PERMISSIONS,
  type Permission,
  mergePermissions,
  hasPermission,
  hasAnyPermission,
  hasAllPermissions,
  getPermissionLabels,
  ROLE_LABELS,
} from "@/lib/permissions";

export {
  PERMISSIONS,
  type Permission,
  mergePermissions,
  hasPermission,
  hasAnyPermission,
  hasAllPermissions,
  getPermissionLabels,
  ROLE_LABELS,
};

const MANAGER_PERMISSIONS: Permission[] = [
  PERMISSIONS.BILLING_READ,
  PERMISSIONS.CREDITS_READ,
  PERMISSIONS.CALL_LOGS_READ,
  PERMISSIONS.CALL_LOGS_WRITE,
  PERMISSIONS.AGENTS_READ,
  PERMISSIONS.AGENTS_WRITE,
  PERMISSIONS.LEADS_READ,
  PERMISSIONS.LEADS_WRITE,
  PERMISSIONS.ANALYTICS_READ,
  PERMISSIONS.ANALYTICS_WRITE,
  PERMISSIONS.INTEGRATIONS_READ,
  PERMISSIONS.NOTIFICATIONS_READ,
  PERMISSIONS.EVENTS_READ,
  PERMISSIONS.SCHEDULER_READ,
  PERMISSIONS.SCHEDULER_WRITE,
  PERMISSIONS.BRANCHES_READ,
  PERMISSIONS.BRANCHES_WRITE,
  PERMISSIONS.DOCUMENTS_READ,
  PERMISSIONS.DOCUMENTS_WRITE,
  PERMISSIONS.EMPLOYEES_READ,
];

const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  OWNER: Object.values(PERMISSIONS),
  ADMIN: Object.values(PERMISSIONS).filter(
    (p) => p !== PERMISSIONS.SETTINGS_WRITE && p !== PERMISSIONS.BRANCHES_BULK,
  ),
  MANAGER: MANAGER_PERMISSIONS,
  SALES: [
    PERMISSIONS.CALL_LOGS_READ,
    PERMISSIONS.CALL_LOGS_WRITE,
    PERMISSIONS.LEADS_READ,
    PERMISSIONS.LEADS_WRITE,
    PERMISSIONS.BRANCHES_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.EVENTS_READ,
  ],
  SUPPORT: [
    PERMISSIONS.CALL_LOGS_READ,
    PERMISSIONS.LEADS_READ,
    PERMISSIONS.BRANCHES_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.EVENTS_READ,
  ],
  AGENT: [
    PERMISSIONS.CREDITS_READ,
    PERMISSIONS.CALL_LOGS_READ,
    PERMISSIONS.AGENTS_READ,
    PERMISSIONS.LEADS_READ,
    PERMISSIONS.LEADS_WRITE,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.EVENTS_READ,
    PERMISSIONS.SCHEDULER_READ,
    PERMISSIONS.BRANCHES_READ,
  ],
};

export function getPermissionsForRole(role: UserRole): Permission[] {
  return ROLE_PERMISSIONS[role] ?? [];
}
